services:
  server:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres-sakila
      - postgres-auth
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command:
      [ "/wait-for-it.sh", "postgres-auth:5432", "-t", "60","--", "sh", "-c",
        "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload" ]

  postgres-sakila:
    image: sakiladb/postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: p_ssW0rd
      POSTGRES_DB: sakila
    volumes:
      - sakila_postgres_data:/var/lib/postgresql/data

  postgres-auth:
    image: postgres:15-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
volumes:
  sakila_postgres_data:
  auth_postgres_data:
  ollama_data: